services:
  vproapp:
    build: 
      context: ./Docker-files/app/ #dockerfile location in curr dir (.)
    image: bhupesh40/vpro-proj-app #repo in dockerhub
    container_name: vproapp #changing container name to match app properties 
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vprodb:
    build: 
      context: ./Docker-files/db/ #dockerfile location in curr dir (.)
    image: bhupesh40/vpro-proj-db #repo in dockerhub
    container_name: vprodb #changing container name to match app properties 
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  vproweb:
    build: 
      context: ./Docker-files/web/ #dockerfile location in curr dir (.)
    image: bhupesh40/vpro-proj-web #repo in dockerhub
    container_name: vproweb #changing container name to match app properties 
    ports:
      - "80:80" 
  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"

volumes:
  vprodbdata: {}
  vproappdata: {}